plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
title: PHIDO-app
markdown: GFM
show_downloads: false
theme:  jekyll-theme-leap-day
