plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
title: Python/Git Workshop
markdown: GFM
show_downloads: true
theme:  jekyll-theme-leap-day
